<?php

function _res_images_image_styles(){
  $styles = array();

  $styles[RESPONSIVE_IMAGE_STYLE] = array(
    'label' => 'Responsive image',
    'effects' => array(
      array(
        'name' => 'image_scale',
        'data' => array(
          'width' => 250,
        ),
        'weight' => 0,
      ),
    ),
  );
  $styles[100] = array(
    'label' => 'Responsive image 100',
    'effects' => array(
      array(
        'name' => 'image_scale',
        'data' => array(
          'width' => 100,
        ),
        'weight' => 0,
      ),
    ),
  );
  $styles[200] = array(
    'label' => 'Responsive image 200',
    'effects' => array(
      array(
        'name' => 'image_scale',
        'data' => array(
          'width' => 200,
        ),
        'weight' => 0,
      ),
    ),
  );
  $styles[300] = array(
    'label' => 'Responsive image 300',
    'effects' => array(
      array(
        'name' => 'image_scale',
        'data' => array(
          'width' => 300,
        ),
        'weight' => 0,
      ),
    ),
  );
  $styles[500] = array(
    'label' => 'Responsive image 500',
    'effects' => array(
      array(
        'name' => 'image_scale',
        'data' => array(
          'width' => 500,
        ),
        'weight' => 0,
      ),
    ),
  );
  $styles[750] = array(
    'label' => 'Responsive image 750',
    'effects' => array(
      array(
        'name' => 'image_scale',
        'data' => array(
          'width' => 750,
        ),
        'weight' => 0,
      ),
    ),
  );
  $styles[1000] = array(
    'label' => 'Responsive image 1000',
    'effects' => array(
      array(
        'name' => 'image_scale',
        'data' => array(
          'width' => 1000,
        ),
        'weight' => 0,
      ),
    ),
  );
  $styles[1250] = array(
    'label' => 'Responsive image 1250',
    'effects' => array(
      array(
        'name' => 'image_scale',
        'data' => array(
          'width' => 1250,
        ),
        'weight' => 0,
      ),
    ),
  );
  $styles[1500] = array(
    'label' => 'Responsive image 1500',
    'effects' => array(
      array(
        'name' => 'image_scale',
        'data' => array(
          'width' => 1500,
        ),
        'weight' => 0,
      ),
    ),
  );
  $styles[1750] = array(
    'label' => 'Responsive image 1750',
    'effects' => array(
      array(
        'name' => 'image_scale',
        'data' => array(
          'width' => 1750,
        ),
        'weight' => 0,
      ),
    ),
  );
  $styles[2000] = array(
    'label' => 'Responsive image 2000',
    'effects' => array(
      array(
        'name' => 'image_scale',
        'data' => array(
          'width' => 2000,
        ),
        'weight' => 0,
      ),
    ),
  );
  $styles[2250] = array(
    'label' => 'Responsive image 2250',
    'effects' => array(
      array(
        'name' => 'image_scale',
        'data' => array(
          'width' => 2250,
        ),
        'weight' => 0,
      ),
    ),
  );
  $styles[2500] = array(
    'label' => 'Responsive image 2500',
    'effects' => array(
      array(
        'name' => 'image_scale',
        'data' => array(
          'width' => 2500,
        ),
        'weight' => 0,
      ),
    ),
  );
  $styles[2750] = array(
    'label' => 'Responsive image 2750',
    'effects' => array(
      array(
        'name' => 'image_scale',
        'data' => array(
          'width' => 2750,
        ),
        'weight' => 0,
      ),
    ),
  );
    $styles[3000] = array(
    'label' => 'Responsive image 3000',
    'effects' => array(
      array(
        'name' => 'image_scale',
        'data' => array(
          'width' => 3000,
        ),
        'weight' => 0,
      ),
    ),
  );
  return $styles;
}

?>
